= Aggregates

In our examples, to begin with, we will use one aggregate - a patient.
We'll model our system such that there are events that get applied on a Patient's timeline.

To uniquely identify a patient, we're assuming, all we need is a `uniqueId`.
No name, no address, no other information.

The rest of the information will be brought in using events.

[source,java,indent=0,role="primary"]
.Java
----
include::{sourcedir}/grooves-example-javaee/src/main/java/grooves/example/javaee/domain/Patient.java[tags=documented]
----
<1> This annotation will assist in checking for completeness of queries.
  There are two other annotations we'll see - `@Event` and `@Query`.
  Together, the three will help us ensure that our queries cover all events.
  This is optional, but highly recommended.

[source,groovy,indent=0,role="secondary"]
.Groovy
----
include::{sourcedir}/grooves-example-springboot-jpa/src/main/groovy/grooves/boot/jpa/domain/Patient.groovy[tags=documented]
----
<1> This annotation will assist in checking for completeness of queries.
  There are two other annotations we'll see - `@Event` and `@Query`.
  Together, the three will help us ensure that our queries cover all events.
  This is optional, but highly recommended.

[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::{sourcedir}/grooves-example-springboot-kotlin/src/main/kotlin/grooves/boot/kotlin/domain/Patient.kt[tags=documented]
----
<1> Since 0.5.0, there isn't really anything special to do for declaring Aggregates.
