= Dependencies

The examples here use gradle to manage dependencies.
You could very well be using Maven, or ant+ivy, or leiningen, or sbt.

[source,groovy,indent=0,role="primary",subs="attributes+"]
.Java
----
repositories {
  // ... other repositories ...
  mavenCentral() // <1>
}
dependencies {
  // ... other dependencies ...
  implementation 'com.github.rahulsom:grooves-java:{gradle-project-version}' // <2>
}
----
<1> In this example, we're using `mavenCentral`. You could also be using `jcenter` or `google`.
  As long as your private artifact repository mirrors `mavenCentral`, you can use that as well.
<2> `grooves-api` contains the interfaces for your queries.
  It has a dependency on `grooves-types`.
  That contains the interfaces for your aggregates, events, and snapshots.

[source,groovy,indent=0,role="secondary",subs="attributes+"]
.Groovy
----
repositories {
  // ... other repositories ...
  mavenCentral() // <1>
}
dependencies {
  // ... other dependencies ...
  implementation 'com.github.rahulsom:grooves-groovy:{gradle-project-version}' // <2>
}
----
<1> In this example, we're using `mavenCentral`. You could also be using `jcenter` or `google`.
  As long as your private artifact repository mirrors `mavenCentral`, you can use that as well.
<2> `grooves-groovy` contains support for writing idiomatic groovy code.
  It has a dependency on `grooves-api` which contains interfaces for your queries.
  It also has a transitive dependency on `grooves-types`.
  That contains the interfaces for your aggregates, events, and snapshots.

[source,groovy,indent=0,role="secondary",subs="attributes+"]
.Kotlin
----
repositories {
  // ... other repositories ...
  mavenCentral() // <1>
}
dependencies {
  // ... other dependencies ...
  implementation 'com.github.rahulsom:grooves-api:{gradle-project-version}' // <2>
}
----
<1> In this example, we're using `mavenCentral`. You could also be using `jcenter` or `google`.
  As long as your private artifact repository mirrors `mavenCentral`, you can use that as well.
<2> `grooves-api` contains the interfaces for your queries.
  It has a dependency on `grooves-types`.
  That contains the interfaces for your aggregates, events, and snapshots.