changelog:
  exclude:
    authors:
      - renovate
      - renovate[bot]
    labels:
      - dependencies
  categories:
    - title: Enhancements
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Test Improvements
      labels:
        - test
    - title: Build/Repo Chores
      labels:
        - chore
    - title: Other
      labels:
        - "*"
