= Changelog

[cols="1,7", options="header"]
|===

| Version | Changes

| 0.5.0
a| * Remove `AggregateType`. Now anything can be an aggregate.
  In GORM, there's a replacement called `GormAggregate`.
  Also remove `QueryT` from most queries.
  Consequently, a lot of interfaces will have to be updated in user code.
* Use PrismJS for docs.
  This allows syntax highlighting for Kotlin code.
* Use `svg-builder` and static type diagramming.
* Vastly improved Null checking using jetbrains annotations.
* OWASP Dependency checking is now routine
* Better syntax highlighting in docs from PrismJS
* Use dependency locking
* Stop relying on Lombok.
  It breaks IDEs sometimes, and build tools sometimes.

| 0.4.0
a| * Make position and timestamp non nullable in Events
* Remove examples for RxGorm REST. It doesn't appear to be well supported.
* Reduce default method reliance for kotlin interfaces.
* Make it easier to contribute to grooves-site.
* Remove `JavaJoin` and `JavaSnapshot` types.
  The `Join` and `Snapshot` types are sufficient.
* Add support for FRP Style queries and push style event sourcing.

| 0.3.0
a| * Support completeness verification in java using annotations.
* Remove `createdBy` and `getAudit`.
  They are too opinionated.
* Use Lombok for Java Examples.
* Use Reactive Streams for APIs.
  This will allow use of RxJava2, Akka and Reactor with ease.
  RxJava1 will involve https://github.com/ReactiveX/RxJavaReactiveStreams[RxReactiveStreams] and take some work.
* Java completeness checks are now supported
* Null checking has been enhanced

| 0.2.1
a| * Allow subclasses in annotations.

| 0.2.0
a| * Joins are now reactive too.
  This removes the need for reattach methods.
* Examples now contains `rx-mongo`.
* Documentation now points to examples.
* Improve Kotlin support.
  Examples and tests for Kotlin have also been added.
* Revert on Merge is now tested and supported.

| 0.1.1
a| * Improve RX support for `rx-gorm-rest`.
  A lot of APIs were returning non observable types.
  Most meaningful calls now return Observables.
* Reduce alignment of API with `gorm-hibernate`.
* Documentation now includes diagrams that are generated from text representation of events.

| 0.1.0
a| * Versioning delegated to nebula.release plugin
* Initial pass of documentation on gh-pages
* RxJava introduced into API.
  This should allow using reactive sources.
* Most API code is now in Java.
  This should improve type support in the IDE significantly.
  Also this opens up the possibility of using Java as a language for users.
* Build system does a lot more static analysis of code.

| 0.0.2
a| * Temporal and Versioned Snapshots are now different.
* Joins are now supported as a special kind of snapshot.

| 0.0.1
a| * Supports Groovy and GORM.
* Contains examples for `rdbms`, `mongo`+`rdbms` and `springboot-jpa`.

|===