https://opensource.org/licenses/Apache-2.0[image:https://img.shields.io/badge/License-Apache%202.0-blue.svg[License]]
https://codecov.io/gh/rahulsom/grooves[image:https://codecov.io/gh/rahulsom/grooves/branch/master/graph/badge.svg[codecov]]

= Grooves

Event Sourcing Library for Java.

_Grooves formerly meant Groovy Event Sourcing._
In its present form, it can support just about any JVM language.
Examples and tests include Java, Groovy and Kotlin.
Documentation can be found https://rahulsom.github.io/grooves/[here].

== Modules

[cols="25%,75%"]
|===

a|grooves-groovy

image::https://maven-badges.herokuapp.com/maven-central/com.github.rahulsom/grooves-groovy/badge.svg[link="https://maven-badges.herokuapp.com/maven-central/com.github.rahulsom/grooves-groovy", width="300px"]
a|This is for you if you want to write your queries in groovy, but are not using GORM.
You will have to implement your own data access, but will get support for checking completeness of queries based on groovy AST Transformations.

a|grooves-java

image::https://maven-badges.herokuapp.com/maven-central/com.github.rahulsom/grooves-java/badge.svg[link="https://maven-badges.herokuapp.com/maven-central/com.github.rahulsom/grooves-java", width="300px"]
a|This is for you if you want to write your queries in java.
You will have to implement your own data access, but will get support for checking completeness of queries based on Annotation Processors.

a|grooves-api

image::https://maven-badges.herokuapp.com/maven-central/com.github.rahulsom/grooves-api/badge.svg[link="https://maven-badges.herokuapp.com/maven-central/com.github.rahulsom/grooves-api", width="300px"]
a|This is for you if you are not using groovy or java, or don't care about verifying completeness of queries.
For example, you could use this for writing code with Kotlin.

a|grooves-types

image::https://maven-badges.herokuapp.com/maven-central/com.github.rahulsom/grooves-types/badge.svg[link="https://maven-badges.herokuapp.com/maven-central/com.github.rahulsom/grooves-types", width="300px"]
a|This contains types that are used in `grooves-api`.
It is very unlikely you'll be using this directly.

a|grooves-diagrams

image::https://maven-badges.herokuapp.com/maven-central/com.github.rahulsom/grooves-diagrams/badge.svg[link="https://maven-badges.herokuapp.com/maven-central/com.github.rahulsom/grooves-diagrams", width="300px"]
a|This is an asciidoctor extension that allows you to generate diagrams like those in grooves' documentation.

|===

== Examples

[cols="1,3"]
|===

|link:examples/springboot/jpa[examples/springboot/jpa]
|This uses Springboot and JPA repositories for everything.
All the code is written in groovy.

|link:examples/springboot/kotlin[examples/springboot/kotlin]
|This uses Spring Reactive Web and RxMongo repositories for everything.
All the code is written in kotlin.

|link:examples/javaee[examples/javaee]
|This uses Java and JavaEE for the APIs.
The persistence here is completely made up using a few `List` objects.
The reason for that is to show how you don't have to be tied to any one persistence mechanism.

|link:examples/pushstyle[examples/pushstyle]
|This uses Kotlin and Guava EventBus.
The snapshots are persisted using jOOQ.
The events are never persisted. They are processed as they come on the EventBus.

|===


== Releasing

* Tag to release. A github action should take care of publishing.
  Remember to update `grooves-site/versions.json` with the correct list of supported versions.
