= Grooves

Event Sourcing Library for Java.

Grooves formerly meant Groovy Event Sourcing.
In its present form, it can support just about any JVM language.
1.0 goals include documentation and testing for Java, Groovy and Kotlin.
Documentation is still a work in progress, but you can see whats available https://rahulsom.github.io/grooves/[here].

== Modules

https://oss.sonatype.org/#nexus-search;quick~grooves-gorm[grooves-gorm]::
    This is for you if you're using GORM for persistence.
    It has interfaces that need to know the domain object used, and build flexible queries without forcing you to write the code to read domain objects from the database.

https://oss.sonatype.org/#nexus-search;quick~grooves-groovy[grooves-groovy]::
    This is for you if you want to write your queries in groovy, but are not using GORM.
    You will have to implement your own data access, but will get support for checking completeness of queries based on groovy AST Transformations.

https://oss.sonatype.org/#nexus-search;quick~grooves-api[grooves-api]::
    This is for you if you are not using groovy, or don't care about verifying completeness of queries.

https://oss.sonatype.org/#nexus-search;quick~grooves-types[grooves-types]::
    This contains types that are used in `grooves-api`.
    It is very unlikely you'll be using this directly.

== Examples

link:examples/grails/rdbms[examples/grails/rdbms]::
   This uses grails (with groovy) backed by Hibernate (through GORM).

link:examples/grails/rdbms_mongo[examples/grails/rdbms_mongo]::
   This uses grails (with groovy) backed by Hibernate (through GORM) for events and aggregates and MongoDB (through GORM) for snapshots.

link:examples/grails/rxmongo[examples/grails/rxmongo]::
   This uses grails (with groovy) backed by MongoDB (through GORM).
   The API is entirely reactive.
   It is based on https://gorm.grails.org/6.0.x/rx/manual/[rx-gorm-mongo].

link:examples/grails/restserver[examples/grails/restserver]::
   This is not exactly an example.
    It is a helper for examples/grails/rxrest

link:examples/grails/rxrest[examples/grails/rxrest]::
   This uses RESTful endpoints for aggregates and events.
   It uses Mongo for snapshots.
   The RESTful part is based on http://gorm.grails.org/latest/rx/rest-client/manual/index.html[rx-gorm-rest].

link:examples/springboot/jpa[examples/springboot/jpa]::
   This uses Springboot and JPA repositories for everything.
   All the code is written in groovy.

link:examples/springboot/kotlin[examples/springboot/kotlin]::
   This uses Spring Reactive Web and RxMongo repositories for everything.
   All the code is written in kotlin.

link:examples/javaee[examples/javaee]::
   This uses Java and JavaEE for the APIs.
   The persistence here is completely made up using a few `List` objects.
   The reason for that is to show how you don't have to be tied to any one persistence mechanism.

