= Grooves
:package: com.github.rahulsom
:package-path: com/github/rahulsom
:package-path-encoded: com%2Fgithub%2Frahulsom
:snapshot-prefix: image:https://img.shields.io/maven-metadata/v?metadataUrl=https%3A%2F%2Fcentral.sonatype.com%2Frepository%2Fmaven-snapshots%2F{package-path-encoded}%2F
:snapshot-middle: %2Fmaven-metadata.xml&style=for-the-badge&label=S[alt=Maven Snapshot,height=30,link="https://central.sonatype.com/repository/maven-snapshots/{package-path}/
:snapshot-suffix: /maven-metadata.xml"]
:central-prefix: image:https://img.shields.io/maven-central/v/{package}/
:central-middle: ?style=for-the-badge&label=R&color=green[alt=Maven Central Version,height=30,link="https://central.sonatype.com/artifact/{package}/
:central-suffix: /overview"]
:deprecated-middle: ?style=for-the-badge&label=R&color=lightgrey[alt=Maven Central Version,height=30,link="https://central.sonatype.com/artifact/{package}/

Event Sourcing Library for Java.

image:https://img.shields.io/github/commits-since/rahulsom/grooves/latest?style=for-the-badge[GitHub commits since latest release, link="https://github.com/rahulsom/grooves/releases/new"]

_Grooves formerly meant Groovy Event Sourcing._
In its present form, it can support just about any JVM language.
Examples and tests include Java, Groovy and Kotlin.
Documentation can be found https://rahulsom.github.io/grooves/[here].

== Modules

=== grooves-types

{central-prefix}grooves-types{central-middle}grooves-types{central-suffix}
{snapshot-prefix}grooves-types{snapshot-middle}grooves-types{snapshot-suffix}

This contains types that are used in `grooves-api`.
It is very unlikely you'll be using this directly.

=== grooves-api

{central-prefix}grooves-api{central-middle}grooves-api{central-suffix}
{snapshot-prefix}grooves-api{snapshot-middle}grooves-api{snapshot-suffix}

This is for you if you are not using groovy or java, or don't care about verifying completeness of queries.
For example, you could use this for writing code with Kotlin.

=== grooves-groovy

{central-prefix}grooves-groovy{central-middle}grooves-groovy{central-suffix}
{snapshot-prefix}grooves-groovy{snapshot-middle}grooves-groovy{snapshot-suffix}

This is for you if you want to write your queries in groovy, but are not using GORM.
You will have to implement your own data access, but will get support for checking completeness of queries based on groovy AST Transformations.

=== grooves-java

{central-prefix}grooves-java{central-middle}grooves-java{central-suffix}
{snapshot-prefix}grooves-java{snapshot-middle}grooves-java{snapshot-suffix}

This is for you if you want to write your queries in java.
You will have to implement your own data access, but will get support for checking completeness of queries based on Annotation Processors.

=== grooves-diagrams

{central-prefix}grooves-diagrams{central-middle}grooves-diagrams{central-suffix}
{snapshot-prefix}grooves-diagrams{snapshot-middle}grooves-diagrams{snapshot-suffix}

This is an asciidoctor extension that allows you to generate diagrams like those in grooves' documentation.

== Examples

[cols="35%,65%"]
|===

|link:grooves-example-springboot-jpa[grooves-example-springboot-jpa]
|This uses Springboot and JPA repositories for everything.
All the code is written in groovy.

|link:grooves-example-springboot-kotlin[grooves-example-springboot-kotlin]
|This uses Spring Reactive Web and RxMongo repositories for everything.
All the code is written in kotlin.

|link:grooves-example-javaee[grooves-example-javaee]
|This uses Java and JavaEE for the APIs.
The persistence here is completely made up using a few `List` objects.
The reason for that is to show how you don't have to be tied to any one persistence mechanism.

|link:grooves-example-pushstyle[grooves-example-pushstyle]
|This uses Kotlin and Guava EventBus.
The snapshots are persisted using jOOQ.
The events are never persisted. They are processed as they come on the EventBus.

|===


== Releasing

* Tag to release. A GitHub action should take care of publishing.
  Remember to update `grooves-site/versions.json` with the correct list of supported versions.
