spring:
    jpa.properties.hibernate.enable_lazy_load_no_trans: true
    output.ansi.enabled: ALWAYS
logging:
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p --- [%15.15t] %-40.40logger{39} : %m%n%wex"
    level:
        root: ERROR
        com.github.rahulsom: DEBUG
        grooves.boot: DEBUG
