= Grooves
:stem:
:nofooter:
:linkcss:
:docinfo: shared

Formerly, _Groovy + Event Sourcing_.
Now, _Grooves_ is just a name.
It supports Event Sourcing on many JVM languages.
Examples and tests are included in java, kotlin, and of course, groovy.

include::{includedir}/intro.adoc[]

include::{includedir}/hurdles.adoc[]

== How Grooves solves it

Grooves assumes nothing about your persistence framework or whether you're building a webapp or a batch application.
Grooves only offers some tools to help you build your own event sourced system.

* Interfaces for the Aggregate, Event (and its special subtypes) and Snapshot.
* A set of interfaces with default methods that help you write queries.
* _If you're using groovy_, annotations to mark these and AST Transformations to ensure all event types are covered in a Query implementation.

This allows you to use Grooves with a lot of different frameworks.
There are examples in the repository for some options you could use.

== Event Sourcing with Grooves

This section contains example code with annotations that indicate what is being done, and why.
We will be using 4 different kinds of projects.

* Java - A java project that uses a few in memory collections as it's storage mechanism.
  It is written in Java 8, and uses JavaEE.
  In the case of Java code, we'll be skipping getters and setters to keep examples concise.
  For the code to actually work, those would be required.
* Groovy - A project that uses SpringBoot and JPA for persistence.
  It's written using Groovy. This uses RxJava2 as the Reactive Streams Framework.
* Kotlin - This is a SpringBoot Reactive Web project that uses RxMongo for persistence.
  This example uses Spring Reactor as the Reactive Streams Framework.

include::{includedir}/examples/dependencies.adoc[]

include::{includedir}/examples/aggregate.adoc[]

include::{includedir}/examples/events.adoc[]

include::{includedir}/examples/snapshot.adoc[]

include::{includedir}/examples/queries.adoc[]

include::{includedir}/examples/joins.adoc[]

include::{includedir}/examples/frp.adoc[]

include::{includedir}/diagramming.adoc[]

include::{includedir}/support.adoc[]
