# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Publish Master

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Gradle Caches
      id: cache-gradle-caches
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-${{hashFiles('**/*.gradle')}}
        path: |
          ~/.gradle/caches

    - name: Cache Gradle Wrapper
      id: cache-gradle-wrapper
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
        path: |
          ~/.gradle/wrapper

    - uses: gradle/wrapper-validation-action@v1
      name: Validate Gradle Wrapper

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Gradle
      env:
        NEXUS_USER: rahulsom
        NEXUS_PASSWORD: ${{secrets.NEXUS_PASSWORD}}
        GRGIT_USER: ${{secrets.GH_TOKEN}}
      run: |
        mkdir -p ~/.gradle
        {
          echo "nexusUsername=$NEXUS_USER"
          echo "nexusPassword=$NEXUS_PASSWORD"
          echo "systemProp.sonar.login=$SONAR_TOKEN"
        } >> ~/.gradle/gradle.properties
        ./gradlew build snapshot asciidoctor sonarqube --stacktrace --scan

    - uses: codecov/codecov-action@v1
      name: Publish Code Coverage