name: Build Master

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Gradle Caches
      id: cache-gradle-caches
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-${{hashFiles('**/*.gradle')}}
        path: |
          ~/.gradle/caches
    - name: Cache Gradle Wrapper
      id: cache-gradle-wrapper
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
        path: |
          ~/.gradle/wrapper
    - uses: gradle/wrapper-validation-action@v1
      name: Validate Gradle Wrapper

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Gradle
      env:
        ORG_GRADLE_PROJECT_sonatypeUsername: rahulsom
        ORG_GRADLE_PROJECT_sonatypePassword: ${{secrets.ORG_GRADLE_PROJECT_sonatypePassword}}
        ORG_GRADLE_PROJECT_signingKey:       ${{secrets.ORG_GRADLE_PROJECT_signingKey}}
        ORG_GRADLE_PROJECT_signingPassword:  ${{secrets.ORG_GRADLE_PROJECT_signingPassword}}
        SONAR_TOKEN:                         ${{secrets.SONAR_TOKEN}}
        GITHUB_TOKEN:                        ${{secrets.GITHUB_TOKEN}}
        GH_TOKEN:                            ${{secrets.GITHUB_TOKEN}}
      run: ./gradlew build snapshot asciidoctor --stacktrace --parallel --scan

    - uses: codecov/codecov-action@v1
      name: Publish Code Coverage